### ISSUE TITLE
getting error on replying msg

### ISSUE THREAD

**Issue by sdwcn** [ImGoodBai/onewebot2#1]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

按正常步骤安装配置后，与bot交互，收到error提示：
**AttributeError: 'str' object has no attribute 'get'
[INFO][2024-08-08 12:16:01][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧)**

### 问题描述 😯

na

### 终端日志 📒

```log
Please press confirm on your phone.
Loading the contact, this may take a little while.
[INFO][2024-08-08 12:15:39][wechat_channel.py:131] - Wechat login success, user_id: @626340e9a186d0904d348461557a90917a3f7e1a9xxxxxxxxxxxxxxxxx, nickname:
Start auto replying.
[INFO][2024-08-08 12:16:00][bridge.py:68] - create bot chatGPT for chat
[INFO][2024-08-08 12:16:00][chat_gpt_bot.py:49] - [CHATGPT] query=你好  你是 ai 么？
[WARNING][2024-08-08 12:16:00][session_manager.py:72] - Exception when counting tokens precisely for prompt: Unknown encoding cl100k_base
[ERROR][2024-08-08 12:16:01][chat_gpt_bot.py:155] - [CHATGPT] Exception: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "bot\chatgpt\chat_gpt_bot.py", line 123, in reply_text
  File "openai\api_resources\chat_completion.py", line 25, in create
  File "openai\api_resources\abstract\engine_api_resource.py", line 153, in create
  File "openai\api_requestor.py", line 298, in request
  File "openai\api_requestor.py", line 700, in _interpret_response
  File "openai\api_requestor.py", line 763, in _interpret_response_line
  File "openai\api_requestor.py", line 418, in handle_error_response
AttributeError: 'str' object has no attribute 'get'
[INFO][2024-08-08 12:16:01][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@e2b2dc7d2196edeae1d3706f1b815fb8857c576ef3072f17c676c9f0d28101d7
```

**Comment by yangyuan-zhen** [comment]
和你一样的问题

**Comment by ImGoodBai** [comment]
稍等我这两天更新新版本。

**Comment by sdwcn** [comment]
大佬，啥时候更新
